/**
 * Node Types Module
 * Defines the various node types used in the knowledge tree and their properties
 */

WebNotebook.KnowledgeTree = WebNotebook.KnowledgeTree || {};
WebNotebook.KnowledgeTree.NodeTypes = (function() {
    // Node type definitions
    const NODE_TYPES = {
        // File node - represents a basic note or document
        file: {
            name: 'File',
            icon: '📄',
            color: '#42a5f5',
            canHaveChildren: false,
            canTrackProgress: true,
            defaultContent: 'This is a file note. You can add your content here.',
            description: 'A basic note or document for storing information',
            editable: true
        },
        
        // Folder node - organizational container
        folder: {
            name: 'Folder',
            icon: '📁',
            color: '#ffa726',
            canHaveChildren: true,
            canTrackProgress: false,
            defaultContent: 'This is a folder that can contain multiple files and notes.',
            description: 'A container for organizing notes and other items',
            editable: true
        },
        
        // Knowledge node - represents a specific concept or topic
        knowledge: {
            name: 'Knowledge Point',
            icon: '💡',
            color: '#66bb6a',
            canHaveChildren: true,
            canTrackProgress: true,
            defaultContent: 'This is a knowledge note that contains specific information about a concept or topic.',
            description: 'A specific concept, idea, or topic that can be connected to other knowledge points',
            editable: true,
            properties: [
                { name: 'difficulty', type: 'select', options: ['Beginner', 'Intermediate', 'Advanced'], default: 'Intermediate' },
                { name: 'importance', type: 'select', options: ['Low', 'Medium', 'High', 'Critical'], default: 'Medium' },
                { name: 'tags', type: 'tags', default: [] }
            ]
        },
        
        // Roadmap node - represents a learning path
        roadmap: {
            name: 'Learning Path',
            icon: '🗺️',
            color: '#ef5350',
            canHaveChildren: true,
            canTrackProgress: true,
            defaultContent: `<h2>Learning Path</h2>
                <p>This is a structured learning roadmap that helps track progress through a sequence of topics.</p>
                <h3>Progress</h3>
                <div class="progress-tracker">
                    <div class="progress-bar-container">
                        <div class="progress-label">Overall Progress:</div>
                        <div class="progress-bar-wrapper">
                            <div class="progress-bar" style="width: 0%;"></div>
                            <div class="progress-percentage">0%</div>
                        </div>
                    </div>
                </div>
                <h3>Learning Steps</h3>
                <p>Define the key learning steps for this roadmap. Right-click and select "New Knowledge Point" to add steps.</p>`,
            description: 'A structured learning path with progress tracking',
            editable: true,
            properties: [
                { name: 'estimatedTime', type: 'text', label: 'Estimated Time', default: '' },
                { name: 'prerequisites', type: 'text', label: 'Prerequisites', default: '' },
                { name: 'level', type: 'select', options: ['Beginner', 'Intermediate', 'Advanced', 'Expert'], default: 'Beginner' }
            ]
        },
        
        // AI-generated note
        'ai-note': {
            name: 'AI Note',
            icon: '🤖',
            color: '#ab47bc',
            canHaveChildren: false,
            canTrackProgress: true,
            defaultContent: 'This is an AI-generated note created by the AI Copilot.',
            description: 'A note generated by the AI assistant',
            editable: true,
            properties: [
                { name: 'generationPrompt', type: 'textarea', label: 'Generation Prompt', default: '' },
                { name: 'sourceContent', type: 'textarea', label: 'Source Content', default: '' }
            ]
        },
        
        // Question node
        question: {
            name: 'Question',
            icon: '❓',
            color: '#8d6e63',
            canHaveChildren: true,
            canTrackProgress: true,
            defaultContent: 'This is a question that needs to be answered.',
            description: 'A question to explore or research',
            editable: true
        },
        
        // External link node
        link: {
            name: 'External Link',
            icon: '🔗',
            color: '#26a69a',
            canHaveChildren: false,
            canTrackProgress: true,
            defaultContent: 'This is a link to an external resource.',
            description: 'A link to an external resource or website',
            editable: true,
            properties: [
                { name: 'url', type: 'text', label: 'URL', default: '' },
                { name: 'description', type: 'textarea', label: 'Description', default: '' }
            ]
        },
        
        // Reference node (e.g., book, article, video)
        reference: {
            name: 'Reference',
            icon: '📚',
            color: '#7e57c2',
            canHaveChildren: false,
            canTrackProgress: true,
            defaultContent: 'This is a reference to an external resource like a book, article, or video.',
            description: 'A reference to a book, article, or other learning material',
            editable: true,
            properties: [
                { name: 'referenceType', type: 'select', options: ['Book', 'Article', 'Video', 'Course', 'Paper', 'Other'], default: 'Book' },
                { name: 'author', type: 'text', label: 'Author', default: '' },
                { name: 'title', type: 'text', label: 'Title', default: '' },
                { name: 'url', type: 'text', label: 'URL', default: '' },
                { name: 'year', type: 'text', label: 'Year', default: '' }
            ]
        }
    };
    
    // Progress status definitions
    const PROGRESS_STATUS = {
        'completed': {
            name: 'Completed',
            icon: '✅',
            color: '#66bb6a',
            description: 'Item has been completed'
        },
        'in-progress': {
            name: 'In Progress',
            icon: '🕓',
            color: '#ffa726',
            description: 'Currently working on this item'
        },
        'not-started': {
            name: 'Not Started',
            icon: '❌',
            color: '#ef5350',
            description: 'Haven\'t started working on this item yet'
        }
    };
    
    /**
     * Get the definition of a specific node type
     * @param {string} type - Node type identifier
     * @returns {Object|null} - Node type definition or null if not found
     */
    function getNodeType(type) {
        return NODE_TYPES[type] || null;
    }
    
    /**
     * Get all available node types
     * @returns {Object} - All node type definitions
     */
    function getAllNodeTypes() {
        return { ...NODE_TYPES };
    }
    
    /**
     * Get nodes that can have children
     * @returns {Array} - Array of node types that can have children
     */
    function getContainerNodeTypes() {
        return Object.entries(NODE_TYPES)
            .filter(([_, typeDef]) => typeDef.canHaveChildren)
            .map(([type, _]) => type);
    }
    
    /**
     * Get node types that can track progress
     * @returns {Array} - Array of node types that can track progress
     */
    function getTrackableNodeTypes() {
        return Object.entries(NODE_TYPES)
            .filter(([_, typeDef]) => typeDef.canTrackProgress)
            .map(([type, _]) => type);
    }
    
    /**
     * Get the icon for a node type
     * @param {string} type - Node type identifier
     * @returns {string} - Icon character for the node type
     */
    function getNodeIcon(type) {
        return NODE_TYPES[type]?.icon || '📄';
    }
    
    /**
     * Get a progress status definition
     * @param {string} status - Status identifier
     * @returns {Object|null} - Status definition or null if not found
     */
    function getProgressStatus(status) {
        return PROGRESS_STATUS[status] || null;
    }
    
    /**
     * Get all progress status definitions
     * @returns {Object} - All progress status definitions
     */
    function getAllProgressStatuses() {
        return { ...PROGRESS_STATUS };
    }
    
    /**
     * Register a new custom node type
     * @param {string} typeId - Unique identifier for the node type
     * @param {Object} definition - Node type definition
     * @returns {boolean} - True if registration was successful
     */
    function registerNodeType(typeId, definition) {
        // Check for required properties
        if (!typeId || !definition || !definition.name || !definition.icon) {
            console.error('Invalid node type definition');
            return false;
        }
        
        // Check if type ID already exists
        if (NODE_TYPES[typeId]) {
            console.error(`Node type "${typeId}" already exists`);
            return false;
        }
        
        // Merge with default properties
        const defaultProps = {
            canHaveChildren: false,
            canTrackProgress: true,
            defaultContent: '',
            description: '',
            editable: true,
            properties: []
        };
        
        NODE_TYPES[typeId] = { ...defaultProps, ...definition };
        
        // Save to storage for persistence
        saveCustomNodeTypes();
        
        return true;
    }
    
    /**
     * Save custom node types to storage
     */
    function saveCustomNodeTypes() {
        // Get only custom node types (not built-in ones)
        const customTypes = {};
        Object.entries(NODE_TYPES).forEach(([typeId, def]) => {
            if (def.custom) {
                customTypes[typeId] = def;
            }
        });
        
        // Save to settings
        const settings = WebNotebook.Utils.Storage.loadSettings();
        settings.customNodeTypes = customTypes;
        WebNotebook.Utils.Storage.saveSettings(settings);
    }
    
    /**
     * Load custom node types from storage
     */
    function loadCustomNodeTypes() {
        const settings = WebNotebook.Utils.Storage.loadSettings();
        
        if (settings.customNodeTypes) {
            Object.entries(settings.customNodeTypes).forEach(([typeId, def]) => {
                // Only add if it doesn't already exist
                if (!NODE_TYPES[typeId]) {
                    NODE_TYPES[typeId] = def;
                }
            });
        }
    }
    
    /**
     * Remove a custom node type
     * @param {string} typeId - ID of the node type to remove
     * @returns {boolean} - True if removal was successful
     */
    function removeNodeType(typeId) {
        // Check if it exists and is a custom type
        if (!NODE_TYPES[typeId] || !NODE_TYPES[typeId].custom) {
            return false;
        }
        
        // Remove from NODE_TYPES
        delete NODE_TYPES[typeId];
        
        // Save changes
        saveCustomNodeTypes();
        
        return true;
    }
    
    // Public API
    return {
        getNodeType,
        getAllNodeTypes,
        getContainerNodeTypes,
        getTrackableNodeTypes,
        getNodeIcon,
        getProgressStatus,
        getAllProgressStatuses,
        registerNodeType,
        removeNodeType,
        loadCustomNodeTypes
    };
})();